### ISSUE TITLE
Launches workspaces instead of search launcher for me

### ISSUE THREAD

**Issue by DetectiveYush** [ManeLippert/gnome-shell-extension-pop-launcher-super-key#2]
I'm on pop os. Pop!_OS 22.04 LTS
I've checked the settings, it's on using super key to launch launcher.
Launches workspaces if the setting is on launcher, applications if it's on workspaces and doesn't respond if on applications. I'm guessing the selection is just mixed up.

**Comment by ManeLippert** [comment]
Hello @DetectiveYush, 

First I apologise to see your issue now but thanks for reaching out to me.

The problem you describe is not related to the extension, because you activate the extension and it should overwrite the handle for the super key and link it back to the launcher. As I forked the extension from `pop-cosmic` I made sure that no other shortcut regarding the workspace or the app menu is in the code. So the extension is the bare minimum to only map the super key and should not have any settings page at all.

The problem itself could be that a other extension of yours manipulates the super key or the workspace and does prevent the extension from remapping. 

I would suggest you disable all your extension and activate only `pop-launcher-super-key` and look if it still not working. I guess it is maybe the pop-cosmic extension itself. The use of both `pop-cosmic` and `pop-launcher-super-key` is not support nor needed because `pop-cosmic` has the same effect as this extension as its origin.

Could you try that for me and report back?

Other than that I have to wait till more user experience this problem to conclude which extension does interfere the remapping of the super key.

**Comment by ManeLippert** [comment]
Since there is no answer I will close the issue but feel free to reopen it again.
